### ISSUE TITLE
Upgrade to 5.22.1

### ISSUE THREAD

**Issue by mwlang** [marjinal1st/medium-editor-rails#16]
Any plans to upgrade to 5.22.1 (latest medium-editor release) soon?

I'm trying to use the medium-editor-insert-plugin and it doesn't work with 5.22.0, but does work with 5.22.1.

**Comment by gabrielmedina** [comment]
Hi my friend. You can make this for us (send me a PR)? In moment, I am very occupied in my job :/

**Comment by mwlang** [comment]
I can fork and issue a pull request for this.

**Comment by mwlang** [comment]
PR #17 issued for this.

**Comment by gabrielmedina** [comment]
Great job!
